### PR TITLE
Add: basic fileupload functionalities

### PR DESCRIPTION
**Pull request by Leo310**
Resolves part of corona-school/project-user#611

**Next steps:**
- Overall better error handling (e.g. backend returns error response)
- Better UI of attached files

**Open questions:**
- "Betreff" and "Deine Nachricht" should be mandatory and "Dateien Anhängen" optional correct?
- What file types should be allowed?
- Atm getting authorization error:
image
- Optional: Maybe support uploading multiple files at once in backend? Would be faster I think

### CODE REVIEW

**Comment by Jonasdoubleyou** [comment]
> "Betreff" and "Deine Nachricht" should be mandatory and "Dateien Anhängen" optional correct?

correct.

> What file types should be allowed?

I don't think we should restrict that.

> Atm getting authorization error

With which testuser and which course? Pupils should only see the contact option when they are actually allowed to contact.

**Comment by Leo310** [comment]
@Jonasdoubleyou it was for testuser pupil1 on course "Lorem Ipsum" :)

**Comment by Jonasdoubleyou** [comment]
True that is a bug, fixed with https://github.com/corona-school/user-app/pull/210

**Comment by Leo310** [comment]
@Jonasdoubleyou what do you think?
I think this is sufficient for now.

**Review by Jonasdoubleyou — COMMENTED** [review]
Very nice! However for some reason it does not work when I contact participants of a course as an instructor. Maybe the files get lost somewhere? (Could be that this is a dev only problem, but we should check)

**Comment by Jonasdoubleyou** [comment]
image

And maybe we can use flexDirection=column for smaller devices?

**Review by Jonasdoubleyou — APPROVED** [review]
nice!

**Pull request merged**
