### PR TITLE
Add legal to welcome and login page.

### PR DESCRIPTION
**Pull request by Maascha**

### CODE REVIEW

**Review by Jonasdoubleyou — APPROVED** [review]

**Review by Jonasdoubleyou — CHANGES_REQUESTED** [review]
Hm, that breaks the layout of the welcome screen image

**Comment by Jonasdoubleyou** [comment]
I think the problem is the 100vw combined with the padding that makes the box overflow. Maybe by using display='flex' on the container and flexGrow='1' on the footer the footer would always stay on the bottom without overflowing

**Comment by Maascha** [comment]
Thanks, good catch. I added a flex container to welcome, but it think for login it worked before, or would you add `display="flex" `  there too?

**Review by Jonasdoubleyou — APPROVED** [review]

**Comment by Jonasdoubleyou** [comment]
Yes, Login looks good

**Pull request merged**
