### PR TITLE
handle incomplete notification messages

### PR DESCRIPTION
**Pull request by jeffersondarcy**

### CODE REVIEW

**Comment by Jonasdoubleyou** [comment]
hm, how is it an error state when the message is null? That can happen i.e. for the Notification 'Login via Email'

**Review by LomyW — APPROVED** [review]
Looks good! 🎉

**Comment by jeffersondarcy** [comment]
> hm, how is it an error state when the message is null? That can happen i.e. for the Notification 'Login via Email' ... Or in case you want to filter out these somewhere else, I guess it's fine to just fail here by throwing an error, this state should then not be reached here

I am not sure what exactly you mean. Should the message be displayed or not, What should I change?

**Review by Jonasdoubleyou — APPROVED** [review]
Yeah this way it should be okay.

**Review by Jonasdoubleyou — APPROVED** [review]

**Pull request merged**
